export const Icons = {
    'bathtub': '/assets/icons/bathtub 1.svg',
    'bed': '/assets/icons/bed 1.svg',
    'bell': '/assets/icons/bell 1.svg',
    'broom': '/assets/icons/broom 1.svg',
    'chef': '/assets/icons/chef 1.svg',
    'credit-card': '/assets/icons/credit-card.svg',
    'date': '/assets/icons/Date.svg',
    'discount': '/assets/icons/DIscount.svg',
    'fav': '/assets/icons/Fav.svg',
    'hot-tub': '/assets/icons/hot-tub.svg',
    'mountain': '/assets/icons/mountain 1.svg',
    'pan': '/assets/icons/pan 1.svg',
    'people': '/assets/icons/people 1.svg',
    'pool': '/assets/icons/pool 1.svg',
    'profile1': '/assets/icons/profile 1.svg',
    'profile2': '/assets/icons/profile 2.svg',
    'shaker': '/assets/icons/shaker 1.svg',
    'share': '/assets/icons/Share.svg',
    'star': '/assets/icons/Star 2.svg',
    'sunrise': '/assets/icons/sunrise 1.svg',
    'wifi': '/assets/icons/wifi 1.svg',
    // Bold
    'map-point': '/assets/icons/Bold/Map & Location/Map Point.svg',
    'lock': '/assets/icons/Bold/Security/Lock.svg',
    // Linear
    'alt-arrow-down': '/assets/icons/Linear/Arrows/Alt Arrow Down.svg',
    'arrow-left': '/assets/icons/Linear/Arrows/Arrow Left.svg',
    'arrow-right': '/assets/icons/Linear/Arrows/Arrow Right.svg',
    'filter': '/assets/icons/Linear/Essentional, UI/Filter.svg',
    'case-minimalistic': '/assets/icons/Linear/School/Case Minimalistic.svg',
    'magnifier': '/assets/icons/Linear/Search/Magnifer.svg',
};

export const Logos = {
    'alx': '/assets/logos/alx_logo.svg',
    'apartment': '/assets/logos/apartment 1.svg',
    'barn': '/assets/logos/barn 1.svg',
    'cabin': '/assets/logos/cabin 1.svg',
    'castle-tower': '/assets/logos/castle-tower 1.svg',
    'cottage': '/assets/logos/cottage 1.svg',
    'farm1': '/assets/logos/farm 1.svg',
    'farm1-1': '/assets/logos/farm 1-1.svg',
    'home': '/assets/logos/home 1.svg',
    'island': '/assets/logos/island (1) 1.svg',
    'key-chain': '/assets/logos/key-chain 1.svg',
    'living-room': '/assets/logos/living-room 1.svg',
    'mansion': '/assets/logos/mansion 1.svg',
    'palm-tree': '/assets/logos/palm-tree 1.svg',
    'swimming-pool': '/assets/logos/swimming-pool 1.svg',
    'tent': '/assets/logos/tent 1.svg',
    'treehouse': '/assets/logos/treehouse (1) 1.svg',
    'vacations': '/assets/logos/vacations 1.svg',
    'villa': '/assets/logos/villa 1.svg',
};

export const HomeImages = {
    'main': '/assets/home_image/Image 1.jpg',
    'mobile': '/assets/home_image/image_mobile.jpg',
};

export const ListingImages = {
    'list1': '/assets/listing_images/List 1.png',
    'list2': '/assets/listing_images/List 2.png',
    'list3': '/assets/listing_images/List 3.png',
    'list4': '/assets/listing_images/List 4.png',
    'list4-1': '/assets/listing_images/List 4-1.png',
    'list6': '/assets/listing_images/List 6.png',
    'list7': '/assets/listing_images/List 7.png',
    'list8': '/assets/listing_images/List 8.png',
    'list9': '/assets/listing_images/List 9.png',
    'list10': '/assets/listing_images/List 10.png',
    'list11': '/assets/listing_images/List 11.png',
    'list12': '/assets/listing_images/List 12.png',
    'list13': '/assets/listing_images/List 13.png',
    'list14': '/assets/listing_images/List 14.png',
    'list15': '/assets/listing_images/List 15.png',
    'list16': '/assets/listing_images/List 16.png',
};

export const DetailImages = {
    'image19': '/assets/detail_images/image 19.png',
    'image21': '/assets/detail_images/image 21.png',
    'image22': '/assets/detail_images/image 22.png',
    'image24': '/assets/detail_images/image 24.png',
    'image25': '/assets/detail_images/image 25.png',
    'image25-1': '/assets/detail_images/image 25-1.png',
    'image25-2': '/assets/detail_images/image 25-2.png',
    'image25-3': '/assets/detail_images/image 25-3.png',
};